package sampling;

import static primitives.Util.isZero;

import java.util.ArrayList;
import java.util.List;

import primitives.Point;
import primitives.Point2D;
import primitives.Vector;

/**
 * Class responsible for representing the sampling area in 3D space
 * (Blackboard). Its primary role is to map normalized 2D offsets into physical
 * 3D points based on its center location and local coordinate system vectors.
 */
public class Blackboard {

	// Position and center of the sampling area in 3D space
	private final Point center;

	// Local coordinate system - two orthogonal and normalized vectors
	private final Vector vUp;
	private final Vector vRight;

	// Physical dimensions of the sampling area
	private final double width;
	private final double height;

	/**
	 * Constructor to construct the Blackboard sampling zone. * @param center The
	 * center point of the area (e.g., pixel center, light source center)
	 * 
	 * @param vUp    Vertical direction vector (will be normalized internally)
	 * @param vRight Horizontal direction vector (will be normalized internally)
	 * @param width  Physical width of the zone (scaled appropriately if needed)
	 * @param height Physical height of the zone (scaled appropriately if needed)
	 */
	public Blackboard(Point center, Vector vUp, Vector vRight, double width, double height) {
		this.center = center;
		// Ensure vectors are fully normalized as required by the project guidelines
		this.vUp = vUp.normalize();
		this.vRight = vRight.normalize();
		this.width = width;
		this.height = height;
	}

	/**
	 * Transforms a list of normalized 2D points (ranging from -0.5 to 0.5)
	 * generated by the SamplingGrid into physical 3D points in the scene space.
	 * * @param gridPoints2D List of normalized 2D coordinates from SamplingGrid
	 * 
	 * @return List of physical 3D target points (Point)
	 */
	public List<Point> convert2DTo3D(List<Point2D> gridPoints2D) {
		// Safety and regression guard: if the list is empty, return at least the center
		// point
		if (gridPoints2D == null || gridPoints2D.isEmpty()) {
			return List.of(this.center);
		}

		List<Point> points3D = new ArrayList<>(gridPoints2D.size());

		for (Point2D wp : gridPoints2D) {
			Point samplePoint = this.center;

			// 1. Calculate and move along the Right axis (2D X-coordinate multiplied by
			// physical width)
			double deltaX = wp.x * this.width;
			if (!isZero(deltaX)) {
				samplePoint = samplePoint.add(this.vRight.scale(deltaX));
			}

			// 2. Calculate and move along the Up axis (2D Y-coordinate multiplied by
			// physical height)
			double deltaY = wp.y * this.height;
			if (!isZero(deltaY)) {
				samplePoint = samplePoint.add(this.vUp.scale(deltaY));
			}

			// Add the final calculated 3D point to the list
			points3D.add(samplePoint);
		}

		return points3D;
	}
}